name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: 1.1.0
  shared_preferences: 2.2.2
  connectivity: 3.0.6
  intl: 0.18.1
  permission_handler: 11.0.1
  jwt_decoder: 2.0.1
  cached_network_image: 3.3.0
  carousel_slider: 4.2.1
  lottie: 2.7.0
  iconsax: 0.0.8
  socket_io_client: 2.0.3+1
  jwt_decode: 0.3.1
  simple_circular_progress_bar: 1.0.2
  flutter_staggered_grid_view: 0.7.0
  shimmer: 3.0.0
  auto_size_text: 3.0.0
  step_progress_indicator: 1.0.2
  get_storage: 2.1.1
  connectivity_plus: 5.0.2
  api_cache_manager: 1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/json/
  fonts: 
    - family: Popin
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
    - family: PopinMedium
      fonts: 
        - asset: fonts/Poppins-Medium.ttf
    - family: PopinSemi
      fonts: 
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true

