name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: 1.1.0
  shared_preferences: 2.2.2
  connectivity: 3.0.6
  intl: 0.18.1
  permission_handler: 11.0.1
  jwt_decoder: 2.0.1
  cached_network_image: 3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

