// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0Fw53pkP-stlQNh3BUjF5cMehIjGMvU',
    appId: '1:419668049249:web:5de21ad217d58229fe1920',
    messagingSenderId: '419668049249',
    projectId: 'todo-da3ef',
    authDomain: 'todo-da3ef.firebaseapp.com',
    storageBucket: 'todo-da3ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz571OzJttr4o5S6IQH3ybqPHk7Kh44wE',
    appId: '1:419668049249:android:1eaedc8d4eef1627fe1920',
    messagingSenderId: '419668049249',
    projectId: 'todo-da3ef',
    storageBucket: 'todo-da3ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgPWZ5sYCiDyDyxfoiNzqqW1bxl-i8E8',
    appId: '1:419668049249:ios:aac687ec09d917fdfe1920',
    messagingSenderId: '419668049249',
    projectId: 'todo-da3ef',
    storageBucket: 'todo-da3ef.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgPWZ5sYCiDyDyxfoiNzqqW1bxl-i8E8',
    appId: '1:419668049249:ios:b3d9fa0ebb35f8d8fe1920',
    messagingSenderId: '419668049249',
    projectId: 'todo-da3ef',
    storageBucket: 'todo-da3ef.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
